platform :ios, '11.4'

target 'ukpd' do
  use_frameworks!

  pod 'Alamofire'

  target 'ukpdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ukpdUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
